CREATE TABLE agent_trace_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    trace_id VARCHAR(100) NOT NULL COMMENT 'Agent调用链路ID',
    conversation_id VARCHAR(200) DEFAULT NULL COMMENT '会话记忆ID',
    user_id VARCHAR(100) DEFAULT NULL COMMENT '用户ID',
    chat_id VARCHAR(100) DEFAULT NULL COMMENT '会话ID',
    user_message TEXT DEFAULT NULL COMMENT '用户原始问题',
    agent_code VARCHAR(50) DEFAULT NULL COMMENT 'Agent编码',
    agent_name VARCHAR(100) DEFAULT NULL COMMENT 'Agent名称',
    stage VARCHAR(50) NOT NULL COMMENT '阶段：chat/router/rag/intent/prompt/tool/agent/fallback',
    event_type VARCHAR(100) NOT NULL COMMENT '事件类型',
    status VARCHAR(30) NOT NULL COMMENT '事件状态：running/success/failed',
    event_data TEXT DEFAULT NULL COMMENT '事件数据JSON',
    error_message TEXT DEFAULT NULL COMMENT '异常信息',
    duration_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    prompt_tokens INT DEFAULT NULL COMMENT 'Prompt token数量，预留字段',
    completion_tokens INT DEFAULT NULL COMMENT 'Completion token数量，预留字段',
    total_tokens INT DEFAULT NULL COMMENT '总token数量，预留字段',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY idx_trace_id (trace_id),
    KEY idx_conversation_id (conversation_id),
    KEY idx_created_time (created_time),
    KEY idx_agent_stage (agent_code, stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent Trace调用链路事件表';
