server:
  port: 18080
spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      redis:
        initialize-schema: true # 初始化向量库结构
        index-name: spring-ai-index # 索引名
        prefix: "embedding:" # 前缀
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/work_aiops_agent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
  data:
    redis:
      host: 192.168.150.101
      password: 123456
      port: 16379 # redis-stack服务
      client-type: jedis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aiops:
  rag:
    knowledge-base-path: docs/rag/theme-business
    biz-domain: theme-business
    fallback-owner-employee-no: THEME_OPS_OWNER
    top-k: 5
    similarity-threshold: 0.65
    chunk-size: 900
    chunk-overlap: 120
    embedding-batch-size: 10
    max-delete-chunks-per-file: 2000
